export const LOCATIONS: { value: string; label: string }[] = [
  // ── States ──────────────────────────────────────────────────────────────────
  { value: "andhra_pradesh", label: "Andhra Pradesh" },
  { value: "arunachal_pradesh", label: "Arunachal Pradesh" },
  { value: "assam", label: "Assam" },
  { value: "bihar", label: "Bihar" },
  { value: "chhattisgarh", label: "Chhattisgarh" },
  { value: "goa", label: "Goa" },
  { value: "gujarat", label: "Gujarat" },
  { value: "haryana", label: "Haryana" },
  { value: "himachal_pradesh", label: "Himachal Pradesh" },
  { value: "jharkhand", label: "Jharkhand" },
  { value: "karnataka", label: "Karnataka" },
  { value: "kerala", label: "Kerala" },
  { value: "madhya_pradesh", label: "Madhya Pradesh" },
  { value: "maharashtra", label: "Maharashtra" },
  { value: "manipur", label: "Manipur" },
  { value: "meghalaya", label: "Meghalaya" },
  { value: "mizoram", label: "Mizoram" },
  { value: "nagaland", label: "Nagaland" },
  { value: "odisha", label: "Odisha" },
  { value: "punjab", label: "Punjab" },
  { value: "rajasthan", label: "Rajasthan" },
  { value: "sikkim", label: "Sikkim" },
  { value: "tamil_nadu", label: "Tamil Nadu" },
  { value: "telangana", label: "Telangana" },
  { value: "tripura", label: "Tripura" },
  { value: "uttar_pradesh", label: "Uttar Pradesh" },
  { value: "uttarakhand", label: "Uttarakhand" },
  { value: "west_bengal", label: "West Bengal" },

  // ── Union Territories ────────────────────────────────────────────────────────
  { value: "andaman_nicobar", label: "Andaman & Nicobar Islands" },
  { value: "chandigarh", label: "Chandigarh" },
  { value: "dadra_nagar_haveli", label: "Dadra & Nagar Haveli and Daman & Diu" },
  { value: "delhi", label: "Delhi (NCT)" },
  { value: "jammu_kashmir", label: "Jammu & Kashmir" },
  { value: "ladakh", label: "Ladakh" },
  { value: "lakshadweep", label: "Lakshadweep" },
  { value: "puducherry", label: "Puducherry" },

  // ── Major Cities ─────────────────────────────────────────────────────────────
  { value: "agra", label: "Agra, Uttar Pradesh" },
  { value: "ahmedabad", label: "Ahmedabad, Gujarat" },
  { value: "ajmer", label: "Ajmer, Rajasthan" },
  { value: "aligarh", label: "Aligarh, Uttar Pradesh" },
  { value: "allahabad", label: "Prayagraj (Allahabad), Uttar Pradesh" },
  { value: "amravati", label: "Amravati, Maharashtra" },
  { value: "amritsar", label: "Amritsar, Punjab" },
  { value: "aurangabad", label: "Aurangabad (Chhatrapati Sambhajinagar), Maharashtra" },
  { value: "bangalore", label: "Bangalore, Karnataka" },
  { value: "bareilly", label: "Bareilly, Uttar Pradesh" },
  { value: "belgaum", label: "Belagavi (Belgaum), Karnataka" },
  { value: "bhopal", label: "Bhopal, Madhya Pradesh" },
  { value: "bhubaneswar", label: "Bhubaneswar, Odisha" },
  { value: "chandigarh_city", label: "Chandigarh City" },
  { value: "chennai", label: "Chennai, Tamil Nadu" },
  { value: "coimbatore", label: "Coimbatore, Tamil Nadu" },
  { value: "cuttack", label: "Cuttack, Odisha" },
  { value: "dehradun", label: "Dehradun, Uttarakhand" },
  { value: "delhi_city", label: "New Delhi, Delhi" },
  { value: "dhanbad", label: "Dhanbad, Jharkhand" },
  { value: "durgapur", label: "Durgapur, West Bengal" },
  { value: "erode", label: "Erode, Tamil Nadu" },
  { value: "faridabad", label: "Faridabad, Haryana" },
  { value: "firozabad", label: "Firozabad, Uttar Pradesh" },
  { value: "ghaziabad", label: "Ghaziabad, Uttar Pradesh" },
  { value: "gorakhpur", label: "Gorakhpur, Uttar Pradesh" },
  { value: "gulbarga", label: "Kalaburagi (Gulbarga), Karnataka" },
  { value: "guntur", label: "Guntur, Andhra Pradesh" },
  { value: "gurgaon", label: "Gurugram (Gurgaon), Haryana" },
  { value: "guwahati", label: "Guwahati, Assam" },
  { value: "gwalior", label: "Gwalior, Madhya Pradesh" },
  { value: "hubli", label: "Hubballi-Dharwad, Karnataka" },
  { value: "hyderabad", label: "Hyderabad, Telangana" },
  { value: "indore", label: "Indore, Madhya Pradesh" },
  { value: "jabalpur", label: "Jabalpur, Madhya Pradesh" },
  { value: "jaipur", label: "Jaipur, Rajasthan" },
  { value: "jalandhar", label: "Jalandhar, Punjab" },
  { value: "jammu_city", label: "Jammu, J&K" },
  { value: "jamshedpur", label: "Jamshedpur, Jharkhand" },
  { value: "jodhpur", label: "Jodhpur, Rajasthan" },
  { value: "kanpur", label: "Kanpur, Uttar Pradesh" },
  { value: "kochi", label: "Kochi, Kerala" },
  { value: "kolhapur", label: "Kolhapur, Maharashtra" },
  { value: "kolkata", label: "Kolkata, West Bengal" },
  { value: "kozhikode", label: "Kozhikode (Calicut), Kerala" },
  { value: "lucknow", label: "Lucknow, Uttar Pradesh" },
  { value: "ludhiana", label: "Ludhiana, Punjab" },
  { value: "madurai", label: "Madurai, Tamil Nadu" },
  { value: "mangalore", label: "Mangaluru (Mangalore), Karnataka" },
  { value: "meerut", label: "Meerut, Uttar Pradesh" },
  { value: "moradabad", label: "Moradabad, Uttar Pradesh" },
  { value: "mumbai", label: "Mumbai, Maharashtra" },
  { value: "mysore", label: "Mysuru (Mysore), Karnataka" },
  { value: "nagpur", label: "Nagpur, Maharashtra" },
  { value: "nashik", label: "Nashik, Maharashtra" },
  { value: "navi_mumbai", label: "Navi Mumbai, Maharashtra" },
  { value: "noida", label: "Noida, Uttar Pradesh" },
  { value: "patna", label: "Patna, Bihar" },
  { value: "pune", label: "Pune, Maharashtra" },
  { value: "raipur", label: "Raipur, Chhattisgarh" },
  { value: "rajkot", label: "Rajkot, Gujarat" },
  { value: "ranchi", label: "Ranchi, Jharkhand" },
  { value: "salem", label: "Salem, Tamil Nadu" },
  { value: "siliguri", label: "Siliguri, West Bengal" },
  { value: "solapur", label: "Solapur, Maharashtra" },
  { value: "srinagar", label: "Srinagar, J&K" },
  { value: "surat", label: "Surat, Gujarat" },
  { value: "thane", label: "Thane, Maharashtra" },
  { value: "thiruvananthapuram", label: "Thiruvananthapuram, Kerala" },
  { value: "tiruchirappalli", label: "Tiruchirappalli (Trichy), Tamil Nadu" },
  { value: "tiruppur", label: "Tiruppur, Tamil Nadu" },
  { value: "udaipur", label: "Udaipur, Rajasthan" },
  { value: "vadodara", label: "Vadodara, Gujarat" },
  { value: "varanasi", label: "Varanasi, Uttar Pradesh" },
  { value: "vijayawada", label: "Vijayawada, Andhra Pradesh" },
  { value: "visakhapatnam", label: "Visakhapatnam, Andhra Pradesh" },
  { value: "warangal", label: "Warangal, Telangana" },
  { value: "other", label: "Other" },
];